### ISSUE TITLE
bin, lib: support electron

### ISSUE THREAD

**Issue by caspervonb** [amokjs/amok#101]
Support for Electron has been mentioned in chat a couple of times, should be fairly trivial to support, just needs to be added to `browser_process` upstream
##

**Comment by caspervonb** [comment]
Added in https://github.com/caspervonb/node-browser_process/commit/a7ab334e5ea2497a080ae7f288d1a2e4f123fdcf, will be available in the next release.

**Comment by caspervonb** [comment]
Upstream support in a patch version

**Comment by caspervonb** [comment]
Probably shouldn't close this until docs and tests are added huh :wink:

**Comment by caspervonb** [comment]
This is in the current master of `browser_process`, where specifying an .html file to browser_process's url option will spawn a tiny shell that opens a window.

**Comment by rgbkrk** [comment]
Very excited for this, based on the project. To the unfamiliar, is any amount of the application state able to stick around?

**Comment by rgbkrk** [comment]
Came here by way of https://github.com/gaearon/react-transform-hmr/issues/49 by the way. Thank you @caspervonb!

**Comment by caspervonb** [comment]
> Very excited for this, based on the project. To the unfamiliar, is any amount of the application state able to stick around?

The runtime state remains completely unchanged

**Comment by rgbkrk** [comment]
*rgbkrk excitedly waits for release*
