### ISSUE TITLE
Logo

### ISSUE THREAD

**Issue by scottcorgan** [amokjs/amok#142]
I'm curious if you think that the current logo would cause confusion with [Divshot's logo](http://divshot.com) (specifically [this one](http://img.crx4chrome.com/5b/1e/ed/lajkckfbiimjdfdfbjgfbdfecnbipdcm-logo.png). It's not exact, but it's pretty similar.

**Comment by caspervonb** [comment]
Someone mentioned renault earlier, so I've been seeing this every time I look at it.

![renault-logo](http://img3.wikia.nocookie.net/__cb20100616085814/logopedia/images/0/06/Renault_logo_1992.png)

When using abstract shapes there's always going to be similarities, an inverted cube is not exactly unique.

But, nothing is final, I got trigger happy wanting to replace what was previously there which was ugly.

There's an issue for this in the org at https://github.com/amokjs/amok-brand/issues/1

**Comment by scottcorgan** [comment]
Ya, no worries. I'm very interested in what's happening to Amok, so I wanted to be proactive.

**Comment by stereokai** [comment]
![amok](https://cloud.githubusercontent.com/assets/2685357/10058909/8b555076-6250-11e5-9e7a-a5fab419206a.png)

**Comment by caspervonb** [comment]
It's babel\s logo? :grin:

**Comment by stereokai** [comment]
Heh, I haven't even remembered Babel also has a brushed typeface - but no, it's not Babels logo. It's very different actually - Text is more italic, more flowing, and BABEL is all caps while this is not. And of course, we have the small .js on the side :)

**Comment by caspervonb** [comment]
Think we should go for something "smoother", and preferably a typeface and a graphical element.
I'm really leaning towards somehow representing a flow, io and/or repl in the graphical element.

**Comment by caspervonb** [comment]
[amok-logo](https://cloud.githubusercontent.com/assets/157787/11881018/2bbfecd4-a53f-11e5-9f94-51224ba3b23b.png)

**Comment by caspervonb** [comment]
Closing this, while I might revise the logo that's basically where we are at.
