### ISSUE TITLE
When using `cordova` with `crosswalk`, can i use `amok`?

### ISSUE THREAD

**Issue by serapath** [amokjs/amok#151]
Hey,

I'm playing with `cordova` and `crosswalk` (bundles a webview based on chrome with your apps)

When visiting `chrome://inspect/#devices` on my laptops chrome browser, I can remote debug my mobile app while it's running on a usb connected android device or the android emulator.

Would it be possible to include `amok` in my workflow to hot reload my app while running on android?

**Comment by caspervonb** [comment]
This is one I can't currently test as I currently have no android device available to me.

Now, it should all be set up to work in theory. Amok can connect to remote tabs and remote debugging ports.

There might be some extra tunneling required with USB, I'm not too sure about that.

**Comment by serapath** [comment]
It's possible to run the android emulator instead.
For now I'm using `browserify-hmr` and `ud` and updating files in my editor hot reloads my cordova based app inside the emulator. It works with my mobile phone too.

In order to work, the `browserify-hmr` plugin takes an `-u` (url) option, which i set to be my current local wifi ip, so the generated client side code "knows" that ip and connects to it in order to receive hot reload updates.

I guess `amok` connects to a running chrome instance instead, which would be the webview running on the mobile device - so I'm not so sure how this could work easily.

**Comment by caspervonb** [comment]
Brief search turned up this https://developer.chrome.com/devtools/docs/remote-debugging#debugging-webviews, to enable debugging webviews. I'll assume it starts a chrome debug server akin to chrome with the remote debugging port option. You're already doing this right? or is this an obsolete step?

If you inspect the target, the websocket address should be in the address bar?

**Comment by caspervonb** [comment]
Alright, acquired a low end android test device. Will be looking into this soon.

**Comment by serapath** [comment]
I have been busy in the last weeks with projects that center around helping refugees in berlin :-)
Currently I'm still using `browserify-hmr` + `ud`, because it works everywhere, but I'm planning to spend some more time to try out `thermite` and `amok` again soon.
I'm venturing more and more into mobile apps using cordova, so if amok would support that option, that would be pretty neat :-)

**Comment by caspervonb** [comment]
Closed in favor of #177, which is actionable.
