### ISSUE TITLE
Implementing dom hotpatching

### ISSUE THREAD

**Issue by xkxx** [amokjs/amok#189]
Hello @caspervonb,

In https://github.com/amokjs/amok/issues/174, you mentioned that you would like to make HTML document hot-swappable in the future. I have some spare time at my hands over the next weeks so I would like to help implement that functionality (along with image/css hotpatching, if time permits).

Looking at https://github.com/shakyShane/html-injector, the way other people have implemented it is:
- At server side, watch the HTML files in file system. When changes happen, diff the DOMs (with something like jsdom or vdom), and send the changeset to browser via socket.io
- At client side, receive and apply the dom updates, ala React

The question is: how would you like it implemented? Looking at the code, there's existing fs watching functionality via chokidar in a plugin, and hotpatch currently uses its own fs.watcher for some reason. Do you want to isolate dom hotpatching in its own plugin as well? How about css/image hotpatching?

Thanks,

xkxx

**Comment by caspervonb** [comment]
Hey @xkxx.

> The question is: how would you like it implemented? Looking at the code, there's existing fs watching functionality via chokidar in a plugin, and hotpatch currently uses its own fs.watcher for some reason. Do you want to isolate dom hotpatching in its own plugin as well? How about css/image hotpatching?

The reason for using `fs.watch` over chokidar was that chokidar is naive and frankly doesn't work as it should. For example it will consider a truncation event a file change event, and ignore the subsequent file change event that's incoming. This lead to races where compiled files would be empty etc.

The `watch` plugin uses chokidar just because I haven't bothered yet, it works *well enough* because generally enough time has passed by the time the client gets the event and does any sort of XHR requests.

It needs to be cleaned up, and will be *soon'ish*

> Looking at https://github.com/shakyShane/html-injector, the way other people have implemented it is:

> At server side, watch the HTML files in file system. When changes happen, diff the DOMs (with something like jsdom or vdom), and send the changeset to browser via socket.io
>  At client side, receive and apply the dom updates, ala React

So, with Amok we already have a server/client websocket connection. The server is the browser, the client is amok.

The simplest way to apply a full DOM diff would probably be to send a `DOM.setOuterHTML` method on the document itself. Chrome already has this functionality so let it do the work. (https://developer.chrome.com/devtools/docs/protocol/1.1/dom#command-setOuterHTML)

Likewise for CSS, `CSS.setStylesheetText` (http://chromedevtools.github.io/debugger-protocol-viewer/CSS/#method-setStyleSheetText) would be a fairly trivial way to update stylesheets.

Images and other resources, would just have to be done by `querySelectorAll` and `dom.setAttributeValue`.

Not too certain if this should go into 'hotpatch' or its own module TBH but in terms of implementation it's probably easier to stick it in its own module.

**Comment by xkxx** [comment]
Thanks @caspervonb !

Thanks for the info on `setOuterHTML`, I don't think replacing the whole document works with dynamic pages though. Say half of your page is React.js and other is static HTML. When you make a change to the static HTML and we replace the whole document, doesn't that wipe out all the React.js as well? I think diffing is better for handling this case.

**Comment by xkxx** [comment]
Also, since js hotpatching, watcher and the upcoming css/image hotpatching plugins are all going to depend on some fs watcher, would it be a good idea to have a centralized fs watcher service so that other plugins may depend upon it?

**Comment by caspervonb** [comment]
> Thanks for the info on setOuterHTML, I don't think replacing the whole document works with dynamic pages though. Say half of your page is React.js and other is static HTML. When you make a change to the static HTML and we replace the whole document, doesn't that wipe out all the React.js as well? I think diffing is better for handling this case.

True, but that's a bit of an esoteric use case. Also it shouldn't really matter since React can just re-render if given a runtime hook.

```js
window.addEventListener('documentUpdate', function() {
  React.render(...);
});
```

You have no way of knowing what was added via devtools, what was added via javascript, and so on so excluding elements gets tricky. Tricky things are hard to document and confuse users.

If you were to do the diff in amok, what would you exclude and what would you include? when is a node 'dirty'?

> Also, since js hotpatching, watcher and the upcoming css/image hotpatching plugins are all going to depend on some fs watcher, would it be a good idea to have a centralized fs watcher service so that other plugins may depend upon it?

Plan was to allow an object stream as an option to these, but it should still be able to bootstrap itself.

I would consider stylesheets and images just another part of document patching. They're just special cases compared to more generic HTML nodes. Without a document that reference these there is nothing to do about it.

**Comment by xkxx** [comment]
Regarding diffing: we don't need to explicitly include/exclude anything. We can keep a copy of HTML (just the file, untouched by devtools and scripts) in cache. When some changes happen, diff the HTML in cache and the latest one, get a list of changes that we need to apply to the dom, then apply them on the browser. Tools like virtual-dom can already do all of these. This way, we can avoid overwriting script/devtools changes as much as possible. The correct working of the diffing approach rests on two assumptions:

1. User's changes to the static html is parallel to those of scripts. This is true in case of using React: people typically let React control one `<div>` in `<body>`, leaving the other nodes in `<body>` as static html. When the user changes the static html, React is unaffected. It's also true in case of typical JQuery scripts that add classes to dom nodes. When the user, say, changes the text of a `<h1>`, the differ applies the text changes but leaves the classes around.
2. When user changes the html file in a way that overwrites changes by the devtools, it's intentional. People often experiment with changes in devtools and apply them to the html file when they are comfortable with it. Besides, now that their changes to the html file applies instantly, there's no need with messing around with dom in devtools anymore.

It's still possible that we accidentally overwrite devtool/script changes, but it only happens when they conflict with the changes on the html file. I don't think they would be very confusing as long as we document them clearly. And in the end they can still re-apply their script changes every time the document gets updated via an event hook.

**Comment by barneycarroll** [comment]
There are many DOM patching libraries out there — try Mithril or Inferno for lightweight but comprehensive — but even among these libraries, the best way to patch is something that continues to be debated and refined.

DOM patching is not what Amok is about. It's about Javascript patching. If you want to hotpatch Javascript and DOM, the way to do it is to write your DOM using a virtual DOM library, run Amok, and tell the DOM library to diff and patch on file change.

**Comment by xkxx** [comment]
Cool - what I think I'll do is to implement both whole-document replacement and diffing in different plugins, and see how they compare. I think both has its own merits and most-suited use cases. At the end of the day they are just plugins, and so we can let the user choose what's better for their applications.

But before that - @caspervonb could you please take a look at https://github.com/caspervonb/node-rdbg/pull/28? The css/image hotpatching relies on having Dom / Css domain interfaces.

**Comment by caspervonb** [comment]
> But before that - @caspervonb could you please take a look at caspervonb/node-rdbg#28? The css/image hotpatching relies on having Dom / Css domain interfaces.

Just use `Client.send` directly for now.

**Comment by caspervonb** [comment]
Ups wrong branch, I meant `Client.request(method, params, callback)`

**Comment by xkxx** [comment]
I have a fairly good idea about how to go about asset hotpatching, and I'll put together a patch around mid March (too busy with schoolwork at the moment).

At document load, [Page.getResourceTree](http://chromedevtools.github.io/debugger-protocol-viewer/Page/#method-getResourceTree) will get us a list of assets on the page. Any subsequent resources loaded via script can be captured via [Network.requestWillBeSent](http://chromedevtools.github.io/debugger-protocol-viewer/Network/#event-requestWillBeSent). We can then fs.watch these assets and when they are changed, force chrome to reload them by adding a `&reload=timestamp` to the src attributes of the dom elements.

One problem with this approach is that if the images are used in css, e.g. `background: src('...')`, then we'll have no way to force reload them. It would be better if we can somehow signal chrome that some resource in the resourceTree is changed, but I couldn't find an API for it, suggesting that chrome might not have that capability at the moment.

**Comment by caspervonb** [comment]
Sounds good.

> One problem with this approach is that if the images are used in css, e.g. background: src('...'), then we'll have no way to force reload them. It would be better if we can somehow signal chrome that some resource in the resourceTree is changed, but I couldn't find an API for it, suggesting that chrome might not have that capability at the moment.

A simple search and replace (maybe a fuzzy search) in the current stylesheets could deal with that scenario pretty well I think? Just keep track of the timestamps so we'll know what to search for.

**Comment by caspervonb** [comment]
Added CSS patching in [https://github.com/codajs/rdbgp-hotpatch](https://github.com/codajs/rdbgp-hotpatch) (library) and [https://github.com/codajs/coda-hotpatch](https://github.com/codajs/coda-hotpatch) (executable)

**Comment by xkxx** [comment]
Cool! Is coda like a more extensible version of amok? Should I plan to submit future patches there from now on?

**Comment by caspervonb** [comment]
Yeah basically making it more modular and "unix" like. Single tools that can be used in combination with each other, or tools I don't even know about. Amok was kind-of built like this but with Coda I'm basically making it "do one thing and do it well".

For example server with browser and hotpatching.
```console
coda server -c 'coda chrome' | coda hotpatch | coda repl
```

It's not too different  from Amok's current option garbage, which looks something like this
```console
amok --browser chrome --server --hotpatch
```

But from a composability standpoint it's way better.

**Comment by xkxx** [comment]
That does look nice!
One question: is the order of the piping significant? Can one do `coda repl | coda hotpatch | coda server -c 'code chrome'`, for example? I looked through the source code and don't really see any actual data being passed from pipe to pipe?

**Comment by caspervonb** [comment]
Right now the order does not matter, each client makes its own connection so the pipes can be replaced with AND.

e.g
```console
coda-chrome & coda-hotpatch
```

Generally there's a one minute timeout before the connection fails (chrome can be slow to start the first time, so it's set rather high)

This may or may not change however, client data may be piped.

**Comment by xkxx** [comment]
I implemented asset hotpatching that I promised a while ago, they currently live on [coda-reloadassets](https://github.com/xkxx/coda-reloadassets) and [rdbgp-reloadassets](https://github.com/xkxx/rdbgp-reloadassets). 

The implementation is pretty straight forward, pretty much word-for-word of what I described a few months ago. It also patches resources that live in stylesheet via search & replace. The heavy-lifting code lives on node.js, keeping track of the assets that the browser has requested, monitoring them and send in a `CustomEvent` when the file changes. The backend also injects a piece of script to the browser itself, which listens to the event and adds the timestamps as necessarily.

While I was writing the backend code, it stroke me how generic it is, it really is an reimplementation of `amok --watch`, except the backend doesn't require a dir path for files to watch for and figure out all that by listening to the browser traffic. A good idea then may be isolating the watcher into its own module so people can implement their custom hotpatch behavior.

There's a demo app - you can try it like so:

```bash
# clone coda-reloadassets
> cd examples/mithril
# launch some static file server
> static -p 3000 &
> google-chrome --remote-debugging-port=3000 http://localhost:3000/ &
> ../../bin/coda reloadassets
```

You will see two images on the web page, an `<img src="/assets/yes.png">` and a `<div style="background: url(/assets/yes.png)"></div>`. As you modify `assets/yes.png`, you should see the changes reflecting on the web page live.

**Comment by caspervonb** [comment]
This bundle is huge, can't add that much to a user's runtime, also I think dumping this on the client side is the wrong approach.

First off, stylesheet properties can be handled with a few calls to `CSS.getStyleSheetText and `CSS.setStyleSheetText`.

Something like the following
```js
Object.keys(styleSheets).forEach(function(key) {
    var styleSheet = styleSheets[key];
    var styleSheetId = styleSheet.styleSheetId;

    client.request('CSS.getStyleSheetText', {
        styleSheetId: styleSheetId,
    }, function(error, text) {
        client.request('CSS.setStyleSheetText', {
            styleSheetId: styleSheetId,
            text: text.replace(/url\(\s*['"]?(.+?)['"]?\s*\)/gi, url),
        }, function(error) {});
    });
});
```

Document attributes can be handled with a few calls to `DOM.querySelectorAll` and `DOM.setAttribute`

```js
var attributes = [
    'src',
    'srcset',
    'poster',
];

attributes.forEach(function(name) {
    client.request('DOM.querySelectorAll', {
        nodeId: nodes['document'].nodeId,
        selector: '[' + name + '*=' + resource.url + ']',
    }, function(error, nodeIds) {
        if (error) {
            /* ... */
        }

        nodeIds.forEach(function(nodeId) {
            client.request('DOM.setAttribute', {
                    nodeId: nodeId,
                    name: name,
                    value: url,
                },
                function(error) {
                    /* */
                });
        });
    });
});
```

**Comment by xkxx** [comment]
I suppose it will be simpler to do it that way. What would you recommend
for accessing styleSheets in a different module? Copying logic from hot
patch sounds bad. Integrating asset reloading into hotpatch is another way,
but they seem like different functionalities that ought to live in
different modules.

**Comment by caspervonb** [comment]
I will be adding it to hotpatch, I know this is the opposite of what I've said previously but user expectations and keeping it simple :wink:

**Comment by xkxx** [comment]
All right, I redid [rdbgp-reloadassets](https://github.com/xkxx/rdbgp-reloadassets), ditched the browser injected script, so that it updates document attributes via remote debugging calls. Could you please take a look at it and see if it's inline with what you have in mind? I can assemble a pull request over the weekend to hotpatch if you'd like.

**Comment by caspervonb** [comment]
Sorry for the late reply, busy busy days.

I need to implement long polling for http(?s) urls for this to be useful, think firing up jekyll or any web app and getting svg icons automatically updated etc.

Also still contemplating how to do general markup updates.
