### ISSUE TITLE
Propagating back changes made in devtools to the code editor

### ISSUE THREAD

**Issue by serapath** [amokjs/amok#191]
Hey, maybe this is the wrong place for this kind of functionality. I wonder if it's possible to use amok to "hot reload" code in my editor that were made in the devtools.
I found this tool that allows that for css http://livestyle.io/
I guess if there is such a ting it would need to respect source maps, but this would be actually a pretty neat feature :-)

**Comment by caspervonb** [comment]
Adding the source folder to the workspace should allow bi-directional updates. Chrome Developer Tools will reload files as they change from the disk. And your editor may reload files as chrome persists them to disk (depends on the editor, you may just be prompted to reload).

Amok might have to deal with source map urls, which it does not currently. I'll look into that but for vanilla scripts it works.
