### ISSUE TITLE
Website is down

### ISSUE THREAD

**Issue by flyfy1** [amokjs/amok#194]
![image](https://cloud.githubusercontent.com/assets/1553760/14734919/449d5de4-08a0-11e6-8f89-65e81acfb4e9.png)

**Comment by caspervonb** [comment]
I am aware :wink: 

![paypal](https://cloud.githubusercontent.com/assets/157787/14736613/9e1eb764-08aa-11e6-8e84-ec9d39de67c7.png)

**Comment by caspervonb** [comment]
Maybe moving it to js.org for the time beingm or just github.io

**Comment by caspervonb** [comment]
It's also available at http://amokjs.github.io/amok/ but seems like I haven't dealt with the path properly.

**Comment by caspervonb** [comment]
So, fixed up my domains and amokjs.com has actually been bought during its grace period by seems to be a squatting agency.

In the not so distant future, a new site will be up at [http://codajs.com](codajs.com) and amok will be forgotten.

**Comment by goldcaddy77** [comment]
Looks like the new amokjs.com is hosting a bunch of malware now, too.  Should probably unlink from the repo description:

![screen shot 2016-07-12 at 2 26 44 pm](https://cloud.githubusercontent.com/assets/573625/16778607/b9aca960-483c-11e6-816b-e1c06aa3358b.png)

**Comment by corysimmons** [comment]
And the Patreon

**Comment by caspervonb** [comment]
Think I've gotten them all now, appreciate it 👍
